export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: "Napolitana",
        description: "Pizza Napolitana con tomates y muzzalmendra.",
        img: "https://t2.rg.ltmcdn.com/es/posts/5/2/6/pizza_napolitana_32625_600.jpg",
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: "Veggie",
        description: "Pizza Veggie con tomate, zuccinni, champiñones, pimientos y muzzalmendra.",
        img: "https://ahumados.shop/wp-content/uploads/2021/04/Whole-Wheat-Veggie-Pizza_EXPS_HCKA19_12558_C10_13_5b-768x768.jpg.webp",
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: "Choclo y cebolla",
        description: "Empanada de choclo y cebolla caramelizada.",
        img: "https://placeralplato.com/files/2015/07/Sorprende-a-todos-con-empanadas-de-choclo-o-humita-caseras-receta-paso-a-paso.jpg",
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: "Acelga",
        description: "Empanada de acelga, espinaca y cebolla caramelizada.",
        img: "https://scm-assets.constant.co/scm/unilever/2bb5223be0548fcc55c230aa5f951219/493f6a8c-ff6f-46e2-b079-a5a530de6405.png",
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: "Choclo y salsa blanca",
        description: "Tarta de choclo, cebolla y salsa blanca a base de leche de avena.",
        img: "https://recetasdetito.com.ar/wp-content/uploads/2020/04/Como-hacer-tarta-de-choclo.png",
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: "Espinaca",
        description: "Tarta de espinaca, cebolla caramelizada y queso de cajú.",
        img: "https://nadirtips.com/wp-content/uploads/2017/02/Tarta-de-Espinaca-www.marubotana.tv_-678x470.jpeg",
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: "Limonada",
        description: "Limonada fresca con menta y jengibre.",
        img: "https://t2.uc.ltmcdn.com/es/posts/0/9/0/como_hacer_limonada_sin_azucar_51090_600.jpg",
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: "Jugo de maracuya",
        description: "Jugo exprimido natural de maracuya y jugo de naranja.",
        img: "https://www.comidasperuanas.vip/wp-content/uploads/2020/03/jugo-de-maracuya.jpg",
        price: 20,
    },
]