export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: "Napolitana",
        description: "Pizza Napolitana con tomates y muzzalmendra.",
        img: "https://t2.rg.ltmcdn.com/es/posts/5/2/6/pizza_napolitana_32625_600.jpg",
        price: 600,
    },
    {
        id: 2,
        category: 1,
        name: "Veggie",
        description: "Pizza Veggie con tomate, zuccinni, champiñones, pimientos y muzzalmendra.",
        img: "https://ahumados.shop/wp-content/uploads/2021/04/Whole-Wheat-Veggie-Pizza_EXPS_HCKA19_12558_C10_13_5b-768x768.jpg.webp",
        price: 650,
    },
    {
        id: 3,
        category: 1,
        name: "Champiñones",
        description: "Pizza con salsa, champiñones y queso de girasol.",
        img: "https://unareceta.com/wp-content/uploads/2014/05/pizza-de-champin%CC%83ones.jpg",
        price: 700,

    },
    {
        id: 4,
        category: 1,
        name: "Palta y Aceitunas",
        description: "Pizza de palta, aceitunas, perejil y queso de tofu.",
        img: "https://parrillerovegetariano.com/wp-content/uploads/2021/01/Pizza-vegetariana-con-masa-de-maiz.png",
        price: 750,

    },
    {
        id: 5,
        category: 2,
        name: "Choclo y cebolla",
        description: "Empanada de choclo y cebolla caramelizada.",
        img: "https://placeralplato.com/files/2015/07/Sorprende-a-todos-con-empanadas-de-choclo-o-humita-caseras-receta-paso-a-paso.jpg",
        price: 50,
    },
    {
        id: 6,
        category: 2,
        name: "Acelga",
        description: "Empanada de acelga, espinaca y cebolla caramelizada.",
        img: "https://scm-assets.constant.co/scm/unilever/2bb5223be0548fcc55c230aa5f951219/493f6a8c-ff6f-46e2-b079-a5a530de6405.png",
        price: 50,
    },
    {
        id: 7,
        category: 2,
        name: "Soja Texturizada",
        description: "Empanada de soja texturizada, aceitunas negras y cebolla caramelizada.",
        img: "http://3.bp.blogspot.com/-0J3JQolOyOA/UxEwmXjrIzI/AAAAAAAAB_M/e1e7TuF5kx4/s1600/Empanadas+presentadas.JPG",
        price: 50,
    },
    {
        id: 8,
        category: 2,
        name: "Calabaza",
        description: "Empanada de calabaza y muzzalmendra.",
        img: "https://recetas.mx/wp-content/uploads/2019/02/1239x697-2.jpg",
        price: 50,
    },
    {
        id: 9,
        category: 3,
        name: "Choclo y salsa blanca",
        description: "Tarta de choclo, cebolla y salsa blanca a base de leche de avena.",
        img: "https://recetasdetito.com.ar/wp-content/uploads/2020/04/Como-hacer-tarta-de-choclo.png",
        price: 1100,
    },
    {
        id: 10,
        category: 3,
        name: "Espinaca",
        description: "Tarta de espinaca, cebolla caramelizada y queso de cajú.",
        img: "https://nadirtips.com/wp-content/uploads/2017/02/Tarta-de-Espinaca-www.marubotana.tv_-678x470.jpeg",
        price: 1000,
    },
    {
        id: 11,
        category: 3,
        name: "Champiñones",
        description: "Tarta de champiñones, puerro y queso de girasol.",
        img: "https://viapais.com.ar/resizer/3v8VuJRC2L2-57x95bLMf5-ioyc=/982x551/smart/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/GBSDCZBWMU4GIMLDGY2WIN3BMU.jpg",
        price: 1500,
    },
    {
        id: 12,
        category: 3,
        name: "Berenjena",
        description: "Tarta de berenjena, cebolla y queso de cajú.",
        img: "https://misrecetasdecocina.net/wp-content/uploads/2017/12/trozo-tarta-de-berenjena.jpg",
        price: 1450,
    },
    {
        id: 13,
        category: 4,
        name: "Limonada",
        description: "Limonada fresca con menta y jengibre.",
        img: "https://t2.uc.ltmcdn.com/es/posts/0/9/0/como_hacer_limonada_sin_azucar_51090_600.jpg",
        price: 400,
    },
    {
        id: 14,
        category: 4,
        name: "Maracuya",
        description: "Jugo exprimido natural de maracuya y jugo de naranja.",
        img: "https://www.comidasperuanas.vip/wp-content/uploads/2020/03/jugo-de-maracuya.jpg",
        price: 540,
    },
    {
        id: 15,
        category: 4,
        name: "Frutos rojos",
        description: "Jugo exprimido natural de frutos rojos y limón.",
        img: "https://cdn7.kiwilimon.com/recetaimagen/38553/49494.jpg",
        price: 500,
    },
    {
        id: 16,
        category: 4,
        name: "Pepino",
        description: "Jugo exprimido natural de pepinos, manzana y espinaca.",
        img: "https://deliciaskitchen.com/wp-content/uploads/2015/09/batido-verde-de-espinacas-con-manzana-y-pepino.jpg",
        price: 460,
    },
]